### ISSUE TITLE
AWS 'loadFromPath' - Reading directory

### ISSUE THREAD

**Issue by wbashir** [nate-strauser/meteor-aws-sdk#1]
Hello Nate,

Thanks for the meteor wrapped object, i am having some difficulty getting 'fs' to read meteor directories from anywhere in the app.  I have a .json file in /config directory at the root of my application. The AWS loadFromPath function uses node.js and the readFileSync internally and for some reason the directory is never found regardless of whether i use a relative path or not ? Do you have any examples where you are able to read using the native 'fs' module ?

**Comment by nate-strauser** [comment]
i dont have any examples using the loadFromPath - i would suggest using `AWS.config.update` instead - you could even put you aws keys/settings into meteor settings and do something like `AWS.config.update(Meteor.settings.AWS)` - you'd have to join your meteor+aws settings, but that might not be a bad thing
