### ISSUE TITLE
Bump to aws-sdk v 1.3.1

### ISSUE THREAD

**Issue by jenschelkopf** [nate-strauser/meteor-aws-sdk#2]
I'd like to use this package, but I need functionality that was added in aws-sdk v1.3.1.  Can you bump the version?

Alternately, is there a way I can do this myself?  I'm new to meteor, but my understanding is that to do this myself I would need to clone this repo, make the version change, and then publish to atmosphere.  Clearly it's better to have one canonical meteor-aws-sdk so I don't want to do that.  Is there a better way?

**Comment by nate-strauser** [comment]
bumped! - its a really simple change to the package.js file but i'm happy to do it

**Comment by jenschelkopf** [comment]
Thanks for the quick response!  Does it take awhile for the updated package to show up in atmosphere?  I removed/added back aws-sdk-npm, and I don't see the change.

**Comment by jenschelkopf** [comment]
I'm still not seeing the version change.  Did you publish it to atmosphere?

**Comment by nate-strauser** [comment]
did you run 'mrt update' ? atmosphere shows the correct version
https://atmosphere.meteor.com/package/aws-sdk-npm

i get this when updating
aws-sdk-npm
    tag: https://github.com/nate-strauser/meteor-aws-sdk.git#v1.3.1

so pretty sure something wrong on your end

**Comment by jenschelkopf** [comment]
I did try running mrt update, but I see the atmosphere package shows the 1.3.1 version.  So I agree it's on my end.  Thanks, I'll look into it.

**Comment by jenschelkopf** [comment]
I was able to get it working - thanks again.
